# Generated by Django 3.0.7 on 2020-06-29 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memberships', '__first__'),
    ]
    
    operations = [
         migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
            ],
          ),  
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=400)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('duration', models.CharField(help_text='please use the following formats : 1 Week or 1 Month', max_length=10)),
                ('starting_date', models.DateField(null=True)),
                ('ending_date', models.DateField(null=True)),
                ('allowed_memberships', models.ManyToManyField(related_name='membershipsallowed', to='memberships.Membership')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Category')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=200, null=True)),
                ('image', models.ImageField(default='cat_images/default.jpg', upload_to='cat_images')),
            ],
        ),
        migrations.CreateModel(
            name='Sujets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('Titre', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=400)),
                ('etabli', models.DateTimeField(auto_now=True)),
                ('image_sujet', models.ImageField(default='default.jpg', upload_to='kurs_images')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Classe')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('Titre', models.CharField(max_length=30)),
                ('video_id', models.CharField(max_length=11)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('position', models.IntegerField()),
                ('cas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Sujets')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Course')),
            ],
        ),
    ]
